use_frameworks!

abstract_target 'Demo' do
  pod 'RealmSwift', '~> 3.14'
  pod 'RxSwift', '~> 5.0'
  pod 'RxCocoa', '~> 5.0'
  pod 'RxRealm', '~> 1.0'
  pod 'RxRealmDataSources', :path => '../'

  target 'RxRealmDataSources_Example' do
    platform :ios, '9.0'
  end

  target 'RxRealmDataSources_MacExample' do
    platform :osx, '10.12'
  end
end

# for the transitional period to swift5.0
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      next unless target.name.include?("RxRealmData")

      config.build_settings['SWIFT_VERSION'] = '5.0'
    end
  end
end
